export const GOSPEL_LOADING = 'GOSPEL_LOADING';
export const ADD_GOSPEL = 'ADD_GOSPEL';
export const GOSPEL_FAILED = 'GOSPEL_FAILED';

export const BIBLE_LOADING = 'BIBLE_LOADING';
export const ADD_BIBLE = 'ADD_BIBLE';
export const BIBLE_FAILED = 'BIBLE_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const NEWTESTAMENT_LOADING = 'NEWTESTAMENT_LOADING';
export const ADD_NEWTESTAMENT = 'ADD_NEWTESTAMENT';
export const NEWTESTAMENT_FAILED = 'NEWTESTAMENT_FAILED';

export const OLDTESTAMENT_LOADING = 'OLDTESTAMENT_LOADING';
export const ADD_OLDTESTAMENT = 'ADD_OLDTESTAMENT';
export const OLDTESTAMENT_FAILED = 'OLDTESTAMENT_FAILED';

export const PARABLES_LOADING = 'PARABLES_LOADING';
export const ADD_PARABLES = 'ADD_PARABLES';
export const PARABLES_FAILED = 'PARABLES_FAILED';

export const PODCASTS_LOADING = 'PODCASTS_LOADING';
export const ADD_PODCASTS = 'ADD_PODCASTS';
export const PODCASTS_FAILED = 'PODCASTS_FAILED';

export const DEVOTIONALS_LOADING = 'DEVOTIONALS_LOADING';
export const ADD_DEVOTIONALS = 'ADD_DEVOTIONALS';
export const DEVOTIONALS_FAILED = 'DEVOTIONALS_FAILED';

export const RADIOSTATIONS_LOADING = 'RADIOSTATIONS_LOADING';
export const ADD_RADIOSTATIONS = 'ADD_RADIOSTATIONS';
export const RADIOSTATIONS_FAILED = 'RADIOSTATIONS_FAILED';

export const TVSERIES_LOADING = 'TVSERIES_LOADING';
export const ADD_TVSERIES = 'ADD_TVSERIES';
export const TVSERIES_FAILED = 'TVSERIES_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

// export const ADD_NOTE = 'ADD_NOTE';
// export const DELETE_NOTE = 'DELETE_NOTE';

